// Code generated by LORD. DO NOT EDIT.
package httpapi

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/marianoceneri/promo-api/internal/compute"
	"github.com/marianoceneri/promo-api/internal/domain"
	"github.com/marianoceneri/promo-api/internal/observability"
	"github.com/marianoceneri/promo-api/internal/store"
)

type Handler struct {
	promotions *store.PromotionStore
	coupons    *store.CouponStore
	engine     compute.Engine
	events     *observability.Recorder
}

func newHandler(engine compute.Engine, promotions *store.PromotionStore, coupons *store.CouponStore) (*Handler, http.Handler) {
	handler := &Handler{promotions: promotions, coupons: coupons, engine: engine, events: observability.NewRecorder()}
	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(w, http.StatusOK, map[string]string{"status": "ok"})
	})
	mux.HandleFunc("GET /_lord/events", func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(w, http.StatusOK, map[string]any{"history_complete": handler.events.HistoryComplete(), "final": true, "events": handler.events.Snapshot()})
	})
	mux.HandleFunc("POST /v1/promotions", handler.createPromotion)
	mux.HandleFunc("PUT /v1/promotions/{id}", handler.updatePromotion)
	mux.HandleFunc("POST /v1/promotions/{id}/publish", handler.publishPromotion)
	mux.HandleFunc("POST /v1/promotions/{id}/archive", handler.archivePromotion)
	mux.HandleFunc("POST /v1/promotions/{id}/disable", handler.disablePromotion)
	mux.HandleFunc("POST /v1/promotions/{id}/enable", handler.enablePromotion)
	mux.HandleFunc("GET /v1/promotions/{id}", handler.getPromotion)
	mux.HandleFunc("GET /v1/promotions", handler.listPromotions)
	mux.HandleFunc("GET /v1/promotions/{id}/validity", handler.checkPromotionValidity)
	mux.HandleFunc("POST /v1/coupons", handler.issueCoupon)
	mux.HandleFunc("GET /v1/coupons/{code}", handler.getCoupon)
	mux.HandleFunc("POST /v1/coupons/{code}/redeem", handler.redeemCoupon)
	mux.HandleFunc("POST /v1/quotes", handler.quoteCart)
	return handler, mux
}

func NewHandler(engine compute.Engine, promotions *store.PromotionStore, coupons *store.CouponStore) http.Handler {
	_, mux := newHandler(engine, promotions, coupons)
	return mux
}

// NewHandlerWithHistory reports whether the event history is complete: a
// service starting over pre-existing persistent state must declare an
// incomplete history so runtime verification stays honest.
func NewHandlerWithHistory(historyComplete bool, engine compute.Engine, promotions *store.PromotionStore, coupons *store.CouponStore) http.Handler {
	handler, mux := newHandler(engine, promotions, coupons)
	if !historyComplete {
		handler.events.MarkHistoryIncomplete()
	}
	return mux
}

func (h *Handler) createPromotion(w http.ResponseWriter, r *http.Request) {
	var value domain.Promotion
	if err := decodeJSON(r, &value); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON body")
		return
	}
	applyPromotionDefaults(&value)
	if err := validatePromotion(value); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	if value.Enabled == true {
		if value.EndsAt.Before(time.Now().UTC()) {
			writeError(w, http.StatusConflict, "enabled=true requires ends_at at or after the request time")
			return
		}
	}
	if err := h.promotions.Create(value); err != nil {
		if errors.Is(err, store.ErrAlreadyExists) {
			writeError(w, http.StatusConflict, "id already exists")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not create promotion")
		return
	}
	w.Header().Set("X-LORD-Event", "PromocionCreada")
	h.events.Record("PromocionCreada", map[string]any{"promotion_id": value.Id})
	writeJSON(w, http.StatusCreated, value)
}

func (h *Handler) updatePromotion(w http.ResponseWriter, r *http.Request) {
	current, err := h.promotions.Get(r.PathValue("id"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get promotion")
		return
	}
	if current.Enabled != true {
		writeError(w, http.StatusConflict, "operation requires enabled=true")
		return
	}
	if current.Status != "draft" && current.Status != "published" {
		writeError(w, http.StatusConflict, "operation requires status in [draft published]")
		return
	}
	var value domain.Promotion
	if err := decodeJSON(r, &value); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON body")
		return
	}
	id := r.PathValue("id")
	if value.Id == "" {
		value.Id = id
	}
	if value.Id != id {
		writeError(w, http.StatusBadRequest, "immutable id does not match path")
		return
	}
	if current.Enabled != value.Enabled {
		writeError(w, http.StatusConflict, "enabled is immutable")
		return
	}
	if value.Status == "" {
		value.Status = current.Status
	}
	if current.Status != value.Status {
		writeError(w, http.StatusConflict, "status is immutable")
		return
	}
	applyPromotionDefaults(&value)
	if err := validatePromotion(value); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	if value.Enabled == true {
		if value.EndsAt.Before(time.Now().UTC()) {
			writeError(w, http.StatusConflict, "enabled=true requires ends_at at or after the request time")
			return
		}
	}
	if err := h.promotions.Update(value); err != nil {
		writeError(w, http.StatusInternalServerError, "could not update promotion")
		return
	}
	w.Header().Set("X-LORD-Event", "PromocionActualizada")
	h.events.Record("PromocionActualizada", map[string]any{"promotion_id": value.Id})
	writeJSON(w, http.StatusOK, value)
}

func (h *Handler) publishPromotion(w http.ResponseWriter, r *http.Request) {
	value, err := h.promotions.Get(r.PathValue("id"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get promotion")
		return
	}
	if value.Status != "draft" {
		writeError(w, http.StatusConflict, "transition requires status=draft")
		return
	}
	value.Status = "published"
	if err := h.promotions.Update(value); err != nil {
		writeError(w, http.StatusInternalServerError, "could not transition promotion")
		return
	}
	w.Header().Set("X-LORD-Event", "PromocionPublicada")
	h.events.Record("PromocionPublicada", map[string]any{"promotion_id": value.Id})
	writeJSON(w, http.StatusOK, value)
}

func (h *Handler) archivePromotion(w http.ResponseWriter, r *http.Request) {
	value, err := h.promotions.Get(r.PathValue("id"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get promotion")
		return
	}
	if value.Status != "published" {
		writeError(w, http.StatusConflict, "transition requires status=published")
		return
	}
	value.Status = "archived"
	if err := h.promotions.Update(value); err != nil {
		writeError(w, http.StatusInternalServerError, "could not transition promotion")
		return
	}
	w.Header().Set("X-LORD-Event", "PromocionArchivada")
	h.events.Record("PromocionArchivada", map[string]any{"promotion_id": value.Id})
	writeJSON(w, http.StatusOK, value)
}

func (h *Handler) disablePromotion(w http.ResponseWriter, r *http.Request) {
	value, err := h.promotions.Get(r.PathValue("id"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get promotion")
		return
	}
	if value.Status != "draft" && value.Status != "published" {
		writeError(w, http.StatusConflict, "operation requires status in [draft published]")
		return
	}
	if value.Enabled != true {
		writeError(w, http.StatusConflict, "transition requires enabled=true")
		return
	}
	value.Enabled = false
	if err := h.promotions.Update(value); err != nil {
		writeError(w, http.StatusInternalServerError, "could not transition promotion")
		return
	}
	w.Header().Set("X-LORD-Event", "PromocionDadaDeBaja")
	h.events.Record("PromocionDadaDeBaja", map[string]any{"promotion_id": value.Id})
	writeJSON(w, http.StatusOK, value)
}

func (h *Handler) enablePromotion(w http.ResponseWriter, r *http.Request) {
	value, err := h.promotions.Get(r.PathValue("id"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get promotion")
		return
	}
	if value.Status != "draft" && value.Status != "published" {
		writeError(w, http.StatusConflict, "operation requires status in [draft published]")
		return
	}
	if value.Enabled != false {
		writeError(w, http.StatusConflict, "transition requires enabled=false")
		return
	}
	value.Enabled = true
	// EnablePromotion always leaves enabled=true, so the clause always applies.
	if value.EndsAt.Before(time.Now().UTC()) {
		writeError(w, http.StatusConflict, "enabled=true requires ends_at at or after the request time")
		return
	}
	if err := h.promotions.Update(value); err != nil {
		writeError(w, http.StatusInternalServerError, "could not transition promotion")
		return
	}
	w.Header().Set("X-LORD-Event", "PromocionRehabilitada")
	h.events.Record("PromocionRehabilitada", map[string]any{"promotion_id": value.Id})
	writeJSON(w, http.StatusOK, value)
}

func (h *Handler) getPromotion(w http.ResponseWriter, r *http.Request) {
	value, err := h.promotions.Get(r.PathValue("id"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get promotion")
		return
	}
	w.Header().Set("X-LORD-Event", "PromocionConsultada")
	h.events.Record("PromocionConsultada", map[string]any{"promotion_id": value.Id})
	writeJSON(w, http.StatusOK, value)
}

func (h *Handler) listPromotions(w http.ResponseWriter, r *http.Request) {
	values := h.promotions.List()
	raw0 := r.URL.Query().Get("enabled")
	if raw0 != "" {
		filter0, err := strconv.ParseBool(raw0)
		if err != nil {
			writeError(w, http.StatusBadRequest, "enabled must be a boolean")
			return
		}
		filtered := values[:0]
		for _, value := range values {
			if value.Enabled == filter0 {
				filtered = append(filtered, value)
			}
		}
		values = filtered
	}
	raw1 := r.URL.Query().Get("status")
	if raw1 != "" {
		filter1 := raw1
		filtered := values[:0]
		for _, value := range values {
			if value.Status == filter1 {
				filtered = append(filtered, value)
			}
		}
		values = filtered
	}
	w.Header().Set("X-LORD-Event", "CatalogoConsultado")
	h.events.Record("CatalogoConsultado", nil)
	writeJSON(w, http.StatusOK, map[string]any{"promotions": values})
}

func (h *Handler) checkPromotionValidity(w http.ResponseWriter, r *http.Request) {
	value, err := h.promotions.Get(r.PathValue("id"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get promotion")
		return
	}
	if value.Status != "published" {
		writeError(w, http.StatusConflict, "operation requires status=published")
		return
	}
	if value.Enabled != true {
		writeError(w, http.StatusConflict, "operation requires enabled=true")
		return
	}
	evaluatedAt, err := time.Parse(time.RFC3339, r.URL.Query().Get("at"))
	if err != nil {
		writeError(w, http.StatusBadRequest, "at must be an RFC3339 timestamp")
		return
	}
	valid := !evaluatedAt.Before(value.StartsAt) && evaluatedAt.Before(value.EndsAt) && value.Enabled
	w.Header().Set("X-LORD-Event", "VigenciaConsultada")
	h.events.Record("VigenciaConsultada", map[string]any{"promotion_id": value.Id})
	writeJSON(w, http.StatusOK, map[string]any{"id": value.Id, "valid": valid, "at": evaluatedAt, "characteristics": value})
}

func (h *Handler) issueCoupon(w http.ResponseWriter, r *http.Request) {
	var value domain.Coupon
	if err := decodeJSON(r, &value); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON body")
		return
	}
	applyCouponDefaults(&value)
	if err := validateCoupon(value); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	if _, err := h.promotions.Get(value.PromotionId); err != nil {
		writeError(w, http.StatusConflict, "promotion_id references a promotion that does not exist")
		return
	}
	viaPromotionId, err := h.promotions.Get(value.PromotionId)
	if err != nil {
		writeError(w, http.StatusConflict, "promotion_id references a promotion that does not exist")
		return
	}
	if viaPromotionId.Status != "published" {
		writeError(w, http.StatusConflict, "operation requires its promotion (via promotion_id) to have status=published")
		return
	}
	if viaPromotionId.Enabled != true {
		writeError(w, http.StatusConflict, "operation requires its promotion (via promotion_id) to have enabled=true")
		return
	}
	if err := h.coupons.Create(value); err != nil {
		if errors.Is(err, store.ErrAlreadyExists) {
			writeError(w, http.StatusConflict, "code already exists")
			return
		}
		if errors.Is(err, store.ErrInvalidReference) {
			writeError(w, http.StatusConflict, "a referenced entity does not exist")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not create coupon")
		return
	}
	w.Header().Set("X-LORD-Event", "CuponEmitido")
	h.events.Record("CuponEmitido", map[string]any{"coupon_code": value.Code, "promotion_id": value.PromotionId})
	writeJSON(w, http.StatusCreated, value)
}

func (h *Handler) getCoupon(w http.ResponseWriter, r *http.Request) {
	value, err := h.coupons.Get(r.PathValue("code"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get coupon")
		return
	}
	w.Header().Set("X-LORD-Event", "CuponConsultado")
	h.events.Record("CuponConsultado", map[string]any{"coupon_code": value.Code, "promotion_id": value.PromotionId})
	writeJSON(w, http.StatusOK, value)
}

func (h *Handler) redeemCoupon(w http.ResponseWriter, r *http.Request) {
	value, err := h.coupons.Get(r.PathValue("code"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get coupon")
		return
	}
	viaPromotionId, err := h.promotions.Get(value.PromotionId)
	if err != nil {
		writeError(w, http.StatusConflict, "promotion_id references a promotion that does not exist")
		return
	}
	if viaPromotionId.Status != "published" {
		writeError(w, http.StatusConflict, "operation requires its promotion (via promotion_id) to have status=published")
		return
	}
	if viaPromotionId.Enabled != true {
		writeError(w, http.StatusConflict, "operation requires its promotion (via promotion_id) to have enabled=true")
		return
	}
	if value.Status != "issued" {
		writeError(w, http.StatusConflict, "transition requires status=issued")
		return
	}
	value.Status = "redeemed"
	policyViaPromotionId, err := h.promotions.Get(value.PromotionId)
	if err != nil {
		writeError(w, http.StatusConflict, "promotion_id references a promotion that does not exist")
		return
	}
	now := time.Now().UTC()
	if now.Before(policyViaPromotionId.StartsAt) || !now.Before(policyViaPromotionId.EndsAt) || !policyViaPromotionId.Enabled {
		writeError(w, http.StatusConflict, "RedeemCoupon requires the promotion referenced by promotion_id to satisfy PromotionValidity")
		return
	}
	if err := h.coupons.Update(value); err != nil {
		writeError(w, http.StatusInternalServerError, "could not transition coupon")
		return
	}
	w.Header().Set("X-LORD-Event", "CuponCanjeado")
	h.events.Record("CuponCanjeado", map[string]any{"coupon_code": value.Code, "promotion_id": value.PromotionId})
	writeJSON(w, http.StatusOK, value)
}

func (h *Handler) quoteCart(w http.ResponseWriter, r *http.Request) {
	var request domain.QuoteRequest
	if err := decodeJSON(r, &request); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON body")
		return
	}
	result, err := h.engine.QuoteCart(request, h.promotions.List())
	if err != nil {
		writeError(w, http.StatusUnprocessableEntity, err.Error())
		return
	}
	if err := compute.VerifyQuoteCart(result); err != nil {
		// The implementation broke a contractual invariant: fail closed rather
		// than return a result the contract does not admit.
		writeError(w, http.StatusInternalServerError, "contract invariant violated: "+err.Error())
		return
	}
	w.Header().Set("X-LORD-Event", "CarritoCotizado")
	h.events.Record("CarritoCotizado", nil)
	writeJSON(w, http.StatusOK, result)
}

func applyPromotionDefaults(value *domain.Promotion) {
	if value.Status == "" {
		value.Status = "draft"
	}
}

func validatePromotion(value domain.Promotion) error {
	if strings.TrimSpace(value.Id) == "" {
		return errors.New("id is required")
	}
	if strings.TrimSpace(value.Name) == "" {
		return errors.New("name is required")
	}
	if value.StartsAt.IsZero() {
		return errors.New("starts_at is required")
	}
	if value.EndsAt.IsZero() {
		return errors.New("ends_at is required")
	}
	if value.Installments < 1 {
		return fmt.Errorf("installments must be at least 1")
	}
	if value.Installments > 48 {
		return fmt.Errorf("installments must be at most 48")
	}
	if value.DiscountPercent < 0 {
		return fmt.Errorf("discount_percent must be at least 0")
	}
	if value.DiscountPercent > 100 {
		return fmt.Errorf("discount_percent must be at most 100")
	}
	if !map[string]bool{"draft": true, "published": true, "archived": true}[value.Status] {
		return errors.New("status has an unsupported value")
	}
	if !value.StartsAt.Before(value.EndsAt) {
		return errors.New("starts_at must precede ends_at")
	}
	return nil
}

func applyCouponDefaults(value *domain.Coupon) {
	if value.Status == "" {
		value.Status = "issued"
	}
}

func validateCoupon(value domain.Coupon) error {
	if strings.TrimSpace(value.Code) == "" {
		return errors.New("code is required")
	}
	if strings.TrimSpace(value.PromotionId) == "" {
		return errors.New("promotion_id is required")
	}
	if !map[string]bool{"issued": true, "redeemed": true}[value.Status] {
		return errors.New("status has an unsupported value")
	}
	return nil
}

func decodeJSON(r *http.Request, target any) error {
	decoder := json.NewDecoder(io.LimitReader(r.Body, 1<<20))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(target); err != nil {
		return err
	}
	if decoder.Decode(&struct{}{}) != io.EOF {
		return errors.New("body must contain one JSON object")
	}
	return nil
}

func writeError(w http.ResponseWriter, status int, message string) {
	writeJSON(w, status, map[string]string{"error": message})
}
func writeJSON(w http.ResponseWriter, status int, payload any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(payload)
}
