// Code generated by LORD. DO NOT EDIT.
package httpapi

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/marianoceneri/promo-api/internal/domain"
	"github.com/marianoceneri/promo-api/internal/observability"
	"github.com/marianoceneri/promo-api/internal/store"
)

type Handler struct {
	promotions *store.PromotionStore
	events     *observability.Recorder
}

func NewHandler(promotions *store.PromotionStore) http.Handler {
	handler := &Handler{promotions: promotions, events: observability.NewRecorder()}
	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(w, http.StatusOK, map[string]string{"status": "ok"})
	})
	mux.HandleFunc("GET /_lord/events", func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(w, http.StatusOK, map[string]any{"history_complete": true, "final": true, "events": handler.events.Snapshot()})
	})
	mux.HandleFunc("POST /v1/promotions", handler.createPromotion)
	mux.HandleFunc("PUT /v1/promotions/{id}", handler.updatePromotion)
	mux.HandleFunc("POST /v1/promotions/{id}/publish", handler.publishPromotion)
	mux.HandleFunc("POST /v1/promotions/{id}/archive", handler.archivePromotion)
	mux.HandleFunc("POST /v1/promotions/{id}/disable", handler.disablePromotion)
	mux.HandleFunc("POST /v1/promotions/{id}/enable", handler.enablePromotion)
	mux.HandleFunc("GET /v1/promotions/{id}", handler.getPromotion)
	mux.HandleFunc("GET /v1/promotions", handler.listPromotions)
	mux.HandleFunc("GET /v1/promotions/{id}/validity", handler.checkPromotionValidity)
	return mux
}

func (h *Handler) createPromotion(w http.ResponseWriter, r *http.Request) {
	var value domain.Promotion
	if err := decodeJSON(r, &value); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON body")
		return
	}
	applyPromotionDefaults(&value)
	if err := validatePromotion(value); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	if value.Enabled == true {
		if value.EndsAt.Before(time.Now().UTC()) {
			writeError(w, http.StatusConflict, "enabled=true requires ends_at at or after the request time")
			return
		}
	}
	if err := h.promotions.Create(value); err != nil {
		if errors.Is(err, store.ErrAlreadyExists) {
			writeError(w, http.StatusConflict, "id already exists")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not create promotion")
		return
	}
	w.Header().Set("X-LORD-Event", "PromocionCreada")
	h.events.Record("PromocionCreada", map[string]any{"promotion_id": value.Id})
	writeJSON(w, http.StatusCreated, value)
}

func (h *Handler) updatePromotion(w http.ResponseWriter, r *http.Request) {
	current, err := h.promotions.Get(r.PathValue("id"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get promotion")
		return
	}
	if current.Enabled != true {
		writeError(w, http.StatusConflict, "operation requires enabled=true")
		return
	}
	if current.Status != "draft" && current.Status != "published" {
		writeError(w, http.StatusConflict, "operation requires status in [draft published]")
		return
	}
	var value domain.Promotion
	if err := decodeJSON(r, &value); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON body")
		return
	}
	id := r.PathValue("id")
	if value.Id == "" {
		value.Id = id
	}
	if value.Id != id {
		writeError(w, http.StatusBadRequest, "immutable id does not match path")
		return
	}
	if current.Enabled != value.Enabled {
		writeError(w, http.StatusConflict, "enabled is immutable")
		return
	}
	if value.Status == "" {
		value.Status = current.Status
	}
	if current.Status != value.Status {
		writeError(w, http.StatusConflict, "status is immutable")
		return
	}
	applyPromotionDefaults(&value)
	if err := validatePromotion(value); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	if value.Enabled == true {
		if value.EndsAt.Before(time.Now().UTC()) {
			writeError(w, http.StatusConflict, "enabled=true requires ends_at at or after the request time")
			return
		}
	}
	if err := h.promotions.Update(value); err != nil {
		writeError(w, http.StatusInternalServerError, "could not update promotion")
		return
	}
	w.Header().Set("X-LORD-Event", "PromocionActualizada")
	h.events.Record("PromocionActualizada", map[string]any{"promotion_id": value.Id})
	writeJSON(w, http.StatusOK, value)
}

func (h *Handler) publishPromotion(w http.ResponseWriter, r *http.Request) {
	value, err := h.promotions.Get(r.PathValue("id"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get promotion")
		return
	}
	if value.Status != "draft" {
		writeError(w, http.StatusConflict, "transition requires status=draft")
		return
	}
	value.Status = "published"
	if err := h.promotions.Update(value); err != nil {
		writeError(w, http.StatusInternalServerError, "could not transition promotion")
		return
	}
	w.Header().Set("X-LORD-Event", "PromocionPublicada")
	h.events.Record("PromocionPublicada", map[string]any{"promotion_id": value.Id})
	writeJSON(w, http.StatusOK, value)
}

func (h *Handler) archivePromotion(w http.ResponseWriter, r *http.Request) {
	value, err := h.promotions.Get(r.PathValue("id"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get promotion")
		return
	}
	if value.Status != "published" {
		writeError(w, http.StatusConflict, "transition requires status=published")
		return
	}
	value.Status = "archived"
	if err := h.promotions.Update(value); err != nil {
		writeError(w, http.StatusInternalServerError, "could not transition promotion")
		return
	}
	w.Header().Set("X-LORD-Event", "PromocionArchivada")
	h.events.Record("PromocionArchivada", map[string]any{"promotion_id": value.Id})
	writeJSON(w, http.StatusOK, value)
}

func (h *Handler) disablePromotion(w http.ResponseWriter, r *http.Request) {
	value, err := h.promotions.Get(r.PathValue("id"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get promotion")
		return
	}
	if value.Status != "draft" && value.Status != "published" {
		writeError(w, http.StatusConflict, "operation requires status in [draft published]")
		return
	}
	if value.Enabled != true {
		writeError(w, http.StatusConflict, "transition requires enabled=true")
		return
	}
	value.Enabled = false
	if err := h.promotions.Update(value); err != nil {
		writeError(w, http.StatusInternalServerError, "could not transition promotion")
		return
	}
	w.Header().Set("X-LORD-Event", "PromocionDadaDeBaja")
	h.events.Record("PromocionDadaDeBaja", map[string]any{"promotion_id": value.Id})
	writeJSON(w, http.StatusOK, value)
}

func (h *Handler) enablePromotion(w http.ResponseWriter, r *http.Request) {
	value, err := h.promotions.Get(r.PathValue("id"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get promotion")
		return
	}
	if value.Status != "draft" && value.Status != "published" {
		writeError(w, http.StatusConflict, "operation requires status in [draft published]")
		return
	}
	if value.Enabled != false {
		writeError(w, http.StatusConflict, "transition requires enabled=false")
		return
	}
	value.Enabled = true
	if value.Enabled == true {
		if value.EndsAt.Before(time.Now().UTC()) {
			writeError(w, http.StatusConflict, "enabled=true requires ends_at at or after the request time")
			return
		}
	}
	if err := h.promotions.Update(value); err != nil {
		writeError(w, http.StatusInternalServerError, "could not transition promotion")
		return
	}
	w.Header().Set("X-LORD-Event", "PromocionRehabilitada")
	h.events.Record("PromocionRehabilitada", map[string]any{"promotion_id": value.Id})
	writeJSON(w, http.StatusOK, value)
}

func (h *Handler) getPromotion(w http.ResponseWriter, r *http.Request) {
	value, err := h.promotions.Get(r.PathValue("id"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get promotion")
		return
	}
	w.Header().Set("X-LORD-Event", "PromocionConsultada")
	h.events.Record("PromocionConsultada", map[string]any{"promotion_id": value.Id})
	writeJSON(w, http.StatusOK, value)
}

func (h *Handler) listPromotions(w http.ResponseWriter, r *http.Request) {
	values := h.promotions.List()
	raw0 := r.URL.Query().Get("enabled")
	if raw0 != "" {
		filter0, err := strconv.ParseBool(raw0)
		if err != nil {
			writeError(w, http.StatusBadRequest, "enabled must be a boolean")
			return
		}
		filtered := values[:0]
		for _, value := range values {
			if value.Enabled == filter0 {
				filtered = append(filtered, value)
			}
		}
		values = filtered
	}
	raw1 := r.URL.Query().Get("status")
	if raw1 != "" {
		filter1 := raw1
		filtered := values[:0]
		for _, value := range values {
			if value.Status == filter1 {
				filtered = append(filtered, value)
			}
		}
		values = filtered
	}
	w.Header().Set("X-LORD-Event", "CatalogoConsultado")
	h.events.Record("CatalogoConsultado", nil)
	writeJSON(w, http.StatusOK, map[string]any{"promotions": values})
}

func (h *Handler) checkPromotionValidity(w http.ResponseWriter, r *http.Request) {
	value, err := h.promotions.Get(r.PathValue("id"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get promotion")
		return
	}
	if value.Status != "published" {
		writeError(w, http.StatusConflict, "operation requires status=published")
		return
	}
	if value.Enabled != true {
		writeError(w, http.StatusConflict, "operation requires enabled=true")
		return
	}
	evaluatedAt, err := time.Parse(time.RFC3339, r.URL.Query().Get("at"))
	if err != nil {
		writeError(w, http.StatusBadRequest, "at must be an RFC3339 timestamp")
		return
	}
	valid := !evaluatedAt.Before(value.StartsAt) && evaluatedAt.Before(value.EndsAt) && value.Enabled
	w.Header().Set("X-LORD-Event", "VigenciaConsultada")
	h.events.Record("VigenciaConsultada", map[string]any{"promotion_id": value.Id})
	writeJSON(w, http.StatusOK, map[string]any{"id": value.Id, "valid": valid, "at": evaluatedAt, "characteristics": value})
}

func applyPromotionDefaults(value *domain.Promotion) {
	if value.Status == "" {
		value.Status = "draft"
	}
}

func validatePromotion(value domain.Promotion) error {
	if strings.TrimSpace(value.Id) == "" {
		return errors.New("id is required")
	}
	if strings.TrimSpace(value.Name) == "" {
		return errors.New("name is required")
	}
	if value.StartsAt.IsZero() {
		return errors.New("starts_at is required")
	}
	if value.EndsAt.IsZero() {
		return errors.New("ends_at is required")
	}
	if value.Installments < 1 {
		return fmt.Errorf("installments must be at least 1")
	}
	if value.Installments > 48 {
		return fmt.Errorf("installments must be at most 48")
	}
	if value.DiscountPercent < 0 {
		return fmt.Errorf("discount_percent must be at least 0")
	}
	if value.DiscountPercent > 100 {
		return fmt.Errorf("discount_percent must be at most 100")
	}
	if !map[string]bool{"draft": true, "published": true, "archived": true}[value.Status] {
		return errors.New("status has an unsupported value")
	}
	if !value.StartsAt.Before(value.EndsAt) {
		return errors.New("starts_at must precede ends_at")
	}
	return nil
}

func decodeJSON(r *http.Request, target any) error {
	decoder := json.NewDecoder(io.LimitReader(r.Body, 1<<20))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(target); err != nil {
		return err
	}
	if decoder.Decode(&struct{}{}) != io.EOF {
		return errors.New("body must contain one JSON object")
	}
	return nil
}

func writeError(w http.ResponseWriter, status int, message string) {
	writeJSON(w, status, map[string]string{"error": message})
}
func writeJSON(w http.ResponseWriter, status int, payload any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(payload)
}
