// Code generated by LORD. DO NOT EDIT.
package httpapi

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/marianoceneri/promo-api/internal/domain"
	"github.com/marianoceneri/promo-api/internal/store"
)

type Handler struct {
	promotions *store.PromotionStore
}

func NewHandler(promotions *store.PromotionStore) http.Handler {
	handler := &Handler{promotions: promotions}
	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(w, http.StatusOK, map[string]string{"status": "ok"})
	})
	mux.HandleFunc("POST /v1/promotions", handler.createPromotion)
	mux.HandleFunc("PUT /v1/promotions/{id}", handler.updatePromotion)
	mux.HandleFunc("GET /v1/promotions/{id}", handler.getPromotion)
	mux.HandleFunc("GET /v1/promotions", handler.listPromotions)
	mux.HandleFunc("GET /v1/promotions/{id}/validity", handler.checkPromotionValidity)
	return mux
}

func (h *Handler) createPromotion(w http.ResponseWriter, r *http.Request) {
	var value domain.Promotion
	if err := decodeJSON(r, &value); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON body")
		return
	}
	applyPromotionDefaults(&value)
	if err := validatePromotion(value); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	if err := h.promotions.Create(value); err != nil {
		if errors.Is(err, store.ErrAlreadyExists) {
			writeError(w, http.StatusConflict, "id already exists")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not create promotion")
		return
	}
	w.Header().Set("X-LORD-Event", "PromocionCreada")
	writeJSON(w, http.StatusCreated, value)
}

func (h *Handler) updatePromotion(w http.ResponseWriter, r *http.Request) {
	var value domain.Promotion
	if err := decodeJSON(r, &value); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON body")
		return
	}
	id := r.PathValue("id")
	if value.Id == "" {
		value.Id = id
	}
	if value.Id != id {
		writeError(w, http.StatusBadRequest, "immutable id does not match path")
		return
	}
	applyPromotionDefaults(&value)
	if err := validatePromotion(value); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	if err := h.promotions.Update(value); err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not update promotion")
		return
	}
	w.Header().Set("X-LORD-Event", "PromocionActualizada")
	writeJSON(w, http.StatusOK, value)
}

func (h *Handler) getPromotion(w http.ResponseWriter, r *http.Request) {
	value, err := h.promotions.Get(r.PathValue("id"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get promotion")
		return
	}
	w.Header().Set("X-LORD-Event", "PromocionConsultada")
	writeJSON(w, http.StatusOK, value)
}

func (h *Handler) listPromotions(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("X-LORD-Event", "CatalogoConsultado")
	writeJSON(w, http.StatusOK, map[string]any{"promotions": h.promotions.List()})
}

func (h *Handler) checkPromotionValidity(w http.ResponseWriter, r *http.Request) {
	value, err := h.promotions.Get(r.PathValue("id"))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusNotFound, "not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "could not get promotion")
		return
	}
	evaluatedAt, err := time.Parse(time.RFC3339, r.URL.Query().Get("at"))
	if err != nil {
		writeError(w, http.StatusBadRequest, "at must be an RFC3339 timestamp")
		return
	}
	valid := !evaluatedAt.Before(value.StartsAt) && evaluatedAt.Before(value.EndsAt) && value.Enabled
	w.Header().Set("X-LORD-Event", "VigenciaConsultada")
	writeJSON(w, http.StatusOK, map[string]any{"id": value.Id, "valid": valid, "at": evaluatedAt, "characteristics": value})
}

func applyPromotionDefaults(value *domain.Promotion) {
	// No defaults.
}

func validatePromotion(value domain.Promotion) error {
	if strings.TrimSpace(value.Id) == "" {
		return errors.New("id is required")
	}
	if strings.TrimSpace(value.Name) == "" {
		return errors.New("name is required")
	}
	if value.StartsAt.IsZero() {
		return errors.New("starts_at is required")
	}
	if value.EndsAt.IsZero() {
		return errors.New("ends_at is required")
	}
	if value.Installments < 1 {
		return fmt.Errorf("installments must be at least 1")
	}
	if value.Installments > 48 {
		return fmt.Errorf("installments must be at most 48")
	}
	if value.DiscountPercent < 0 {
		return fmt.Errorf("discount_percent must be at least 0")
	}
	if value.DiscountPercent > 100 {
		return fmt.Errorf("discount_percent must be at most 100")
	}
	if !value.StartsAt.Before(value.EndsAt) {
		return errors.New("starts_at must precede ends_at")
	}
	return nil
}

func decodeJSON(r *http.Request, target any) error {
	decoder := json.NewDecoder(io.LimitReader(r.Body, 1<<20))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(target); err != nil {
		return err
	}
	if decoder.Decode(&struct{}{}) != io.EOF {
		return errors.New("body must contain one JSON object")
	}
	return nil
}

func writeError(w http.ResponseWriter, status int, message string) {
	writeJSON(w, status, map[string]string{"error": message})
}
func writeJSON(w http.ResponseWriter, status int, payload any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(payload)
}
