// Code generated by LORD. DO NOT EDIT.
package httpapi

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/marianoceneri/promo-api/internal/store"
)

func TestPromotionContractFlow(t *testing.T) {
	handler := NewHandler(store.NewPromotionStore())
	request := httptest.NewRequest(http.MethodPost, "/v1/promotions", bytes.NewReader([]byte("{\"id\":\"PROMO-TEST\",\"name\":\"name-test\",\"starts_at\":\"2030-01-01T00:00:00Z\",\"ends_at\":\"2031-01-01T00:00:00Z\",\"installments\":1,\"discount_percent\":1,\"enabled\":true}")))
	response := httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusCreated {
		t.Fatalf("create status = %d, body = %s", response.Code, response.Body.String())
	}
	if response.Header().Get("X-LORD-Event") != "PromocionCreada" {
		t.Fatal("create did not emit its contractual event")
	}
	request = httptest.NewRequest(http.MethodGet, "/v1/promotions/PROMO-TEST", nil)
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusOK {
		t.Fatalf("get status = %d, body = %s", response.Code, response.Body.String())
	}
	if response.Header().Get("X-LORD-Event") != "PromocionConsultada" {
		t.Fatal("get did not emit its contractual event")
	}
	request = httptest.NewRequest(http.MethodGet, "/v1/promotions/PROMO-TEST/validity?at=2030-06-01T00%3A00%3A00Z", nil)
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusOK {
		t.Fatalf("validity status = %d, body = %s", response.Code, response.Body.String())
	}
	var result struct {
		Valid bool `json:"valid"`
	}
	if err := json.Unmarshal(response.Body.Bytes(), &result); err != nil {
		t.Fatal(err)
	}
	if !result.Valid {
		t.Fatal("expected generated fixture to be valid")
	}
	if response.Header().Get("X-LORD-Event") != "VigenciaConsultada" {
		t.Fatal("validity check did not emit its contractual event")
	}
	request = httptest.NewRequest(http.MethodPost, "/v1/promotions/PROMO-TEST/disable", nil)
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusOK {
		t.Fatalf("DisablePromotion status = %d, body = %s", response.Code, response.Body.String())
	}
	if response.Header().Get("X-LORD-Event") != "PromocionDadaDeBaja" {
		t.Fatal("DisablePromotion did not emit its contractual event")
	}
	request = httptest.NewRequest(http.MethodPut, "/v1/promotions/PROMO-TEST", bytes.NewReader([]byte("{\"id\":\"PROMO-TEST\",\"name\":\"name-test\",\"starts_at\":\"2030-01-01T00:00:00Z\",\"ends_at\":\"2031-01-01T00:00:00Z\",\"installments\":1,\"discount_percent\":1,\"enabled\":true}")))
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusConflict {
		t.Fatalf("UpdatePromotion after DisablePromotion status = %d, want 409", response.Code)
	}
	request = httptest.NewRequest(http.MethodGet, "/v1/promotions/PROMO-TEST/validity?at=2030-06-01T00%3A00%3A00Z", nil)
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusConflict {
		t.Fatalf("CheckPromotionValidity after DisablePromotion status = %d, want 409", response.Code)
	}
	request = httptest.NewRequest(http.MethodGet, "/v1/promotions?enabled=false", nil)
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusOK || !strings.Contains(response.Body.String(), "PROMO-TEST") {
		t.Fatalf("ListPromotions matching filter did not return transitioned entity: %s", response.Body.String())
	}
	request = httptest.NewRequest(http.MethodGet, "/v1/promotions?enabled=true", nil)
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusOK || strings.Contains(response.Body.String(), "PROMO-TEST") {
		t.Fatalf("ListPromotions opposite filter returned transitioned entity: %s", response.Body.String())
	}
	request = httptest.NewRequest(http.MethodPost, "/v1/promotions/PROMO-TEST/enable", nil)
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusOK {
		t.Fatalf("EnablePromotion status = %d, body = %s", response.Code, response.Body.String())
	}
	if response.Header().Get("X-LORD-Event") != "PromocionRehabilitada" {
		t.Fatal("EnablePromotion did not emit its contractual event")
	}
	request = httptest.NewRequest(http.MethodGet, "/v1/promotions?enabled=true", nil)
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusOK || !strings.Contains(response.Body.String(), "PROMO-TEST") {
		t.Fatalf("ListPromotions matching filter did not return transitioned entity: %s", response.Body.String())
	}
	request = httptest.NewRequest(http.MethodGet, "/v1/promotions?enabled=false", nil)
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusOK || strings.Contains(response.Body.String(), "PROMO-TEST") {
		t.Fatalf("ListPromotions opposite filter returned transitioned entity: %s", response.Body.String())
	}
	request = httptest.NewRequest(http.MethodGet, "/_lord/events", nil)
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusOK {
		t.Fatalf("events status = %d, body = %s", response.Code, response.Body.String())
	}
	var events struct {
		Events []struct {
			Type string         `json:"type"`
			Data map[string]any `json:"data"`
		} `json:"events"`
	}
	if err := json.Unmarshal(response.Body.Bytes(), &events); err != nil {
		t.Fatal(err)
	}
	if len(events.Events) == 0 {
		t.Fatal("expected structured LORD runtime events")
	}
	if events.Events[0].Data["promotion_id"] != "PROMO-TEST" {
		t.Fatalf("missing runtime correlation: %#v", events.Events[0].Data)
	}
}

func TestPromotionInstallmentsContractBoundaries(t *testing.T) {
	cases := []struct {
		name string
		body string
		want int
	}{
		{name: "minimum", body: "{\"id\":\"PROMOTION-INSTALLMENTS-minimum\",\"name\":\"name-test\",\"starts_at\":\"2030-01-01T00:00:00Z\",\"ends_at\":\"2031-01-01T00:00:00Z\",\"installments\":1,\"discount_percent\":1,\"enabled\":true}", want: http.StatusCreated},
		{name: "below_minimum", body: "{\"id\":\"PROMOTION-INSTALLMENTS-below_minimum\",\"name\":\"name-test\",\"starts_at\":\"2030-01-01T00:00:00Z\",\"ends_at\":\"2031-01-01T00:00:00Z\",\"installments\":0,\"discount_percent\":1,\"enabled\":true}", want: http.StatusBadRequest},
		{name: "maximum", body: "{\"id\":\"PROMOTION-INSTALLMENTS-maximum\",\"name\":\"name-test\",\"starts_at\":\"2030-01-01T00:00:00Z\",\"ends_at\":\"2031-01-01T00:00:00Z\",\"installments\":48,\"discount_percent\":1,\"enabled\":true}", want: http.StatusCreated},
		{name: "above_maximum", body: "{\"id\":\"PROMOTION-INSTALLMENTS-above_maximum\",\"name\":\"name-test\",\"starts_at\":\"2030-01-01T00:00:00Z\",\"ends_at\":\"2031-01-01T00:00:00Z\",\"installments\":49,\"discount_percent\":1,\"enabled\":true}", want: http.StatusBadRequest},
	}
	for _, test := range cases {
		t.Run(test.name, func(t *testing.T) {
			handler := NewHandler(store.NewPromotionStore())
			request := httptest.NewRequest(http.MethodPost, "/v1/promotions", bytes.NewReader([]byte(test.body)))
			response := httptest.NewRecorder()
			handler.ServeHTTP(response, request)
			if response.Code != test.want {
				t.Fatalf("status = %d, want %d, body = %s", response.Code, test.want, response.Body.String())
			}
		})
	}
}

func TestPromotionDiscountPercentContractBoundaries(t *testing.T) {
	cases := []struct {
		name string
		body string
		want int
	}{
		{name: "minimum", body: "{\"id\":\"PROMOTION-DISCOUNTPERCENT-minimum\",\"name\":\"name-test\",\"starts_at\":\"2030-01-01T00:00:00Z\",\"ends_at\":\"2031-01-01T00:00:00Z\",\"installments\":1,\"discount_percent\":0,\"enabled\":true}", want: http.StatusCreated},
		{name: "below_minimum", body: "{\"id\":\"PROMOTION-DISCOUNTPERCENT-below_minimum\",\"name\":\"name-test\",\"starts_at\":\"2030-01-01T00:00:00Z\",\"ends_at\":\"2031-01-01T00:00:00Z\",\"installments\":1,\"discount_percent\":-1,\"enabled\":true}", want: http.StatusBadRequest},
		{name: "maximum", body: "{\"id\":\"PROMOTION-DISCOUNTPERCENT-maximum\",\"name\":\"name-test\",\"starts_at\":\"2030-01-01T00:00:00Z\",\"ends_at\":\"2031-01-01T00:00:00Z\",\"installments\":1,\"discount_percent\":100,\"enabled\":true}", want: http.StatusCreated},
		{name: "above_maximum", body: "{\"id\":\"PROMOTION-DISCOUNTPERCENT-above_maximum\",\"name\":\"name-test\",\"starts_at\":\"2030-01-01T00:00:00Z\",\"ends_at\":\"2031-01-01T00:00:00Z\",\"installments\":1,\"discount_percent\":101,\"enabled\":true}", want: http.StatusBadRequest},
	}
	for _, test := range cases {
		t.Run(test.name, func(t *testing.T) {
			handler := NewHandler(store.NewPromotionStore())
			request := httptest.NewRequest(http.MethodPost, "/v1/promotions", bytes.NewReader([]byte(test.body)))
			response := httptest.NewRecorder()
			handler.ServeHTTP(response, request)
			if response.Code != test.want {
				t.Fatalf("status = %d, want %d, body = %s", response.Code, test.want, response.Body.String())
			}
		})
	}
}

func TestPromotionEnabledIsImmutable(t *testing.T) {
	handler := NewHandler(store.NewPromotionStore())
	request := httptest.NewRequest(http.MethodPost, "/v1/promotions", bytes.NewReader([]byte("{\"id\":\"PROMO-TEST\",\"name\":\"name-test\",\"starts_at\":\"2030-01-01T00:00:00Z\",\"ends_at\":\"2031-01-01T00:00:00Z\",\"installments\":1,\"discount_percent\":1,\"enabled\":true}")))
	response := httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusCreated {
		t.Fatalf("create status = %d", response.Code)
	}
	request = httptest.NewRequest(http.MethodPut, "/v1/promotions/PROMO-TEST", bytes.NewReader([]byte("{\"id\":\"PROMO-TEST\",\"name\":\"name-test\",\"starts_at\":\"2030-01-01T00:00:00Z\",\"ends_at\":\"2031-01-01T00:00:00Z\",\"installments\":1,\"discount_percent\":1,\"enabled\":false}")))
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusConflict {
		t.Fatalf("immutable update status = %d, want 409", response.Code)
	}
}

func TestPromotionCreatePromotionPrecondition(t *testing.T) {
	cases := []struct {
		name string
		body string
		want int
	}{
		{name: "expired_blocked", body: "{\"id\":\"PROMOTION-PRE-EXPIRED\",\"name\":\"name-test\",\"starts_at\":\"2000-01-01T00:00:00Z\",\"ends_at\":\"2000-02-01T00:00:00Z\",\"installments\":1,\"discount_percent\":1,\"enabled\":true}", want: http.StatusConflict},
		{name: "future_allowed", body: "{\"id\":\"PROMOTION-PRE-FUTURE\",\"name\":\"name-test\",\"starts_at\":\"2030-01-01T00:00:00Z\",\"ends_at\":\"2999-01-01T00:00:00Z\",\"installments\":1,\"discount_percent\":1,\"enabled\":true}", want: http.StatusCreated},
		{name: "expired_unguarded_allowed", body: "{\"id\":\"PROMOTION-PRE-UNGUARDED\",\"name\":\"name-test\",\"starts_at\":\"2000-01-01T00:00:00Z\",\"ends_at\":\"2000-02-01T00:00:00Z\",\"installments\":1,\"discount_percent\":1,\"enabled\":false}", want: http.StatusCreated},
	}
	for _, test := range cases {
		t.Run(test.name, func(t *testing.T) {
			handler := NewHandler(store.NewPromotionStore())
			request := httptest.NewRequest(http.MethodPost, "/v1/promotions", bytes.NewReader([]byte(test.body)))
			response := httptest.NewRecorder()
			handler.ServeHTTP(response, request)
			if response.Code != test.want {
				t.Fatalf("status = %d, want %d, body = %s", response.Code, test.want, response.Body.String())
			}
		})
	}
}

func TestPromotionUpdatePromotionPrecondition(t *testing.T) {
	handler := NewHandler(store.NewPromotionStore())
	request := httptest.NewRequest(http.MethodPost, "/v1/promotions", bytes.NewReader([]byte("{\"id\":\"PROMOTION-PRE-UPDATE\",\"name\":\"name-test\",\"starts_at\":\"2030-01-01T00:00:00Z\",\"ends_at\":\"2999-01-01T00:00:00Z\",\"installments\":1,\"discount_percent\":1,\"enabled\":true}")))
	response := httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusCreated {
		t.Fatalf("create status = %d, body = %s", response.Code, response.Body.String())
	}
	request = httptest.NewRequest(http.MethodPut, "/v1/promotions/PROMOTION-PRE-UPDATE", bytes.NewReader([]byte("{\"id\":\"PROMOTION-PRE-UPDATE\",\"name\":\"name-test\",\"starts_at\":\"2000-01-01T00:00:00Z\",\"ends_at\":\"2000-02-01T00:00:00Z\",\"installments\":1,\"discount_percent\":1,\"enabled\":true}")))
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusConflict {
		t.Fatalf("expired update status = %d, want 409, body = %s", response.Code, response.Body.String())
	}
}

func TestPromotionEnablePromotionPrecondition(t *testing.T) {
	handler := NewHandler(store.NewPromotionStore())
	request := httptest.NewRequest(http.MethodPost, "/v1/promotions", bytes.NewReader([]byte("{\"id\":\"PROMOTION-PRE-TRANSITION\",\"name\":\"name-test\",\"starts_at\":\"2000-01-01T00:00:00Z\",\"ends_at\":\"2000-02-01T00:00:00Z\",\"installments\":1,\"discount_percent\":1,\"enabled\":false}")))
	response := httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusCreated {
		t.Fatalf("create status = %d, body = %s", response.Code, response.Body.String())
	}
	request = httptest.NewRequest(http.MethodPost, "/v1/promotions/PROMOTION-PRE-TRANSITION/enable", nil)
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusConflict {
		t.Fatalf("expired transition status = %d, want 409, body = %s", response.Code, response.Body.String())
	}
}
