// Code generated by LORD. DO NOT EDIT.
package main

import (
	"log"
	"net/http"

	"github.com/marianoceneri/promo-api/internal/httpapi"
	"github.com/marianoceneri/promo-api/internal/store"
)

func main() {
	promotionStore := store.NewPromotionStore()
	handler := httpapi.NewHandler(promotionStore)
	log.Printf("promo-api listening on :8080")
	log.Fatal(http.ListenAndServe(":8080", handler))
}
