// Code generated by LORD. DO NOT EDIT.
package store

import (
	"errors"
	"sort"
	"sync"

	"github.com/marianoceneri/promo-api/internal/domain"
)

var (
	ErrNotFound      = errors.New("not found")
	ErrAlreadyExists = errors.New("already exists")
)

type PromotionStore struct {
	mu    sync.RWMutex
	items map[string]domain.Promotion
}

func NewPromotionStore() *PromotionStore {
	return &PromotionStore{items: make(map[string]domain.Promotion)}
}

func (s *PromotionStore) Create(value domain.Promotion) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, exists := s.items[value.Id]; exists {
		return ErrAlreadyExists
	}
	s.items[value.Id] = value
	return nil
}

func (s *PromotionStore) Update(value domain.Promotion) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, exists := s.items[value.Id]; !exists {
		return ErrNotFound
	}
	s.items[value.Id] = value
	return nil
}

func (s *PromotionStore) Get(id string) (domain.Promotion, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	value, exists := s.items[id]
	if !exists {
		return domain.Promotion{}, ErrNotFound
	}
	return value, nil
}

func (s *PromotionStore) List() []domain.Promotion {
	s.mu.RLock()
	defer s.mu.RUnlock()
	result := make([]domain.Promotion, 0, len(s.items))
	for _, value := range s.items {
		result = append(result, value)
	}
	sort.Slice(result, func(i, j int) bool { return result[i].Id < result[j].Id })
	return result
}
