// Code generated by LORD. DO NOT EDIT.
package store

import (
	"database/sql"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	_ "modernc.org/sqlite"

	"github.com/marianoceneri/promo-api/internal/domain"
)

func OpenDatabase(path string) (*sql.DB, error) {
	if dir := filepath.Dir(path); dir != "." && dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return nil, err
		}
	}
	db, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, err
	}
	db.SetMaxOpenConns(1)
	if _, err := db.Exec("PRAGMA journal_mode = WAL; PRAGMA busy_timeout = 5000; PRAGMA foreign_keys = ON;"); err != nil {
		db.Close()
		return nil, err
	}
	return db, nil
}

func NewTestDatabase() *sql.DB {
	db, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		panic(err)
	}
	db.SetMaxOpenConns(1)
	if _, err := db.Exec("PRAGMA foreign_keys = ON;"); err != nil {
		panic(err)
	}
	if err := MigrateDatabase(db); err != nil {
		panic(err)
	}
	return db
}

// DatabaseHasRows reports whether any contract-managed table already holds
// data: a fresh process over pre-existing rows has an incomplete event
// history and must declare it.
func DatabaseHasRows(db *sql.DB) (bool, error) {
	for _, table := range []string{"promotions", "coupons"} {
		var populated int64
		if err := db.QueryRow("SELECT EXISTS(SELECT 1 FROM " + table + " LIMIT 1)").Scan(&populated); err != nil {
			if strings.Contains(err.Error(), "no such table") {
				continue
			}
			return false, err
		}
		if populated != 0 {
			return true, nil
		}
	}
	return false, nil
}

// MigrateDatabase creates missing tables and adds missing columns derived
// from the active contract. Columns present in the database but absent from
// the contract abort with an explicit error: destructive migrations require
// operator action, never an automatic drop.
func MigrateDatabase(db *sql.DB) error {
	{
		if _, err := db.Exec("CREATE TABLE IF NOT EXISTS promotions (id TEXT NOT NULL PRIMARY KEY, name TEXT NOT NULL, starts_at TEXT NOT NULL, ends_at TEXT NOT NULL, installments INTEGER NOT NULL, discount_percent INTEGER NOT NULL, enabled INTEGER NOT NULL, status TEXT NOT NULL)"); err != nil {
			return err
		}
		existing, err := tableColumns(db, "promotions")
		if err != nil {
			return err
		}
		expected := []struct{ name, clause string }{
			{"id", "TEXT NOT NULL DEFAULT ''"},
			{"name", "TEXT NOT NULL DEFAULT ''"},
			{"starts_at", "TEXT NOT NULL DEFAULT ''"},
			{"ends_at", "TEXT NOT NULL DEFAULT ''"},
			{"installments", "INTEGER NOT NULL DEFAULT 0"},
			{"discount_percent", "INTEGER NOT NULL DEFAULT 0"},
			{"enabled", "INTEGER NOT NULL DEFAULT 0"},
			{"status", "TEXT NOT NULL DEFAULT ''"},
		}
		known := map[string]bool{}
		for _, column := range expected {
			known[column.name] = true
			if !existing[column.name] {
				if _, err := db.Exec("ALTER TABLE promotions ADD COLUMN " + column.name + " " + column.clause); err != nil {
					return err
				}
			}
		}
		for name := range existing {
			if !known[name] {
				return fmt.Errorf("table promotions has column %q outside the active contract; destructive migrations require explicit operator action", name)
			}
		}
	}

	{
		if _, err := db.Exec("CREATE TABLE IF NOT EXISTS coupons (code TEXT NOT NULL PRIMARY KEY, promotion_id TEXT NOT NULL, status TEXT NOT NULL, FOREIGN KEY (promotion_id) REFERENCES promotions(id))"); err != nil {
			return err
		}
		existing, err := tableColumns(db, "coupons")
		if err != nil {
			return err
		}
		expected := []struct{ name, clause string }{
			{"code", "TEXT NOT NULL DEFAULT ''"},
			{"promotion_id", "TEXT NOT NULL DEFAULT ''"},
			{"status", "TEXT NOT NULL DEFAULT ''"},
		}
		known := map[string]bool{}
		for _, column := range expected {
			known[column.name] = true
			if !existing[column.name] {
				if _, err := db.Exec("ALTER TABLE coupons ADD COLUMN " + column.name + " " + column.clause); err != nil {
					return err
				}
			}
		}
		for name := range existing {
			if !known[name] {
				return fmt.Errorf("table coupons has column %q outside the active contract; destructive migrations require explicit operator action", name)
			}
		}
	}
	return nil
}

func tableColumns(db *sql.DB, table string) (map[string]bool, error) {
	rows, err := db.Query("PRAGMA table_info(" + table + ")")
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	columns := map[string]bool{}
	for rows.Next() {
		var id int64
		var name, columnType string
		var notNull, primaryKey int64
		var defaultValue any
		if err := rows.Scan(&id, &name, &columnType, &notNull, &defaultValue, &primaryKey); err != nil {
			return nil, err
		}
		columns[name] = true
	}
	return columns, rows.Err()
}

type PromotionStore struct{ db *sql.DB }

func NewPromotionStore(db *sql.DB) *PromotionStore { return &PromotionStore{db: db} }

func (s *PromotionStore) Create(value domain.Promotion) error {
	_, err := s.db.Exec("INSERT INTO promotions (id, name, starts_at, ends_at, installments, discount_percent, enabled, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", value.Id, value.Name, formatStoredTime(value.StartsAt), formatStoredTime(value.EndsAt), value.Installments, value.DiscountPercent, storedBool(value.Enabled), value.Status)
	if err != nil {
		if strings.Contains(err.Error(), "UNIQUE constraint failed") {
			return ErrAlreadyExists
		}
		if strings.Contains(err.Error(), "FOREIGN KEY constraint failed") {
			return ErrInvalidReference
		}
		return err
	}
	return nil
}

func (s *PromotionStore) Update(value domain.Promotion) error {
	result, err := s.db.Exec("UPDATE promotions SET name = ?, starts_at = ?, ends_at = ?, installments = ?, discount_percent = ?, enabled = ?, status = ? WHERE id = ?", value.Name, formatStoredTime(value.StartsAt), formatStoredTime(value.EndsAt), value.Installments, value.DiscountPercent, storedBool(value.Enabled), value.Status, value.Id)
	if err != nil {
		return err
	}
	affected, err := result.RowsAffected()
	if err != nil {
		return err
	}
	if affected == 0 {
		return ErrNotFound
	}
	return nil
}

func (s *PromotionStore) Get(id string) (domain.Promotion, error) {
	return scanPromotion(s.db.QueryRow("SELECT id, name, starts_at, ends_at, installments, discount_percent, enabled, status FROM promotions WHERE id = ?", id))
}

func (s *PromotionStore) List() []domain.Promotion {
	result := make([]domain.Promotion, 0)
	rows, err := s.db.Query("SELECT id, name, starts_at, ends_at, installments, discount_percent, enabled, status FROM promotions ORDER BY id")
	if err != nil {
		return result
	}
	defer rows.Close()
	for rows.Next() {
		value, err := scanPromotion(rows)
		if err != nil {
			return result
		}
		result = append(result, value)
	}
	return result
}

func scanPromotion(row interface{ Scan(dest ...any) error }) (domain.Promotion, error) {
	var value domain.Promotion
	var startsAtRaw string
	var endsAtRaw string
	var enabledRaw int64
	if err := row.Scan(&value.Id, &value.Name, &startsAtRaw, &endsAtRaw, &value.Installments, &value.DiscountPercent, &enabledRaw, &value.Status); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return domain.Promotion{}, ErrNotFound
		}
		return domain.Promotion{}, err
	}
	value.StartsAt = parseStoredTime(startsAtRaw)
	value.EndsAt = parseStoredTime(endsAtRaw)
	value.Enabled = enabledRaw != 0
	return value, nil
}

type CouponStore struct{ db *sql.DB }

func NewCouponStore(db *sql.DB) *CouponStore { return &CouponStore{db: db} }

func (s *CouponStore) Create(value domain.Coupon) error {
	_, err := s.db.Exec("INSERT INTO coupons (code, promotion_id, status) VALUES (?, ?, ?)", value.Code, value.PromotionId, value.Status)
	if err != nil {
		if strings.Contains(err.Error(), "UNIQUE constraint failed") {
			return ErrAlreadyExists
		}
		if strings.Contains(err.Error(), "FOREIGN KEY constraint failed") {
			return ErrInvalidReference
		}
		return err
	}
	return nil
}

func (s *CouponStore) Update(value domain.Coupon) error {
	result, err := s.db.Exec("UPDATE coupons SET promotion_id = ?, status = ? WHERE code = ?", value.PromotionId, value.Status, value.Code)
	if err != nil {
		return err
	}
	affected, err := result.RowsAffected()
	if err != nil {
		return err
	}
	if affected == 0 {
		return ErrNotFound
	}
	return nil
}

func (s *CouponStore) Get(id string) (domain.Coupon, error) {
	return scanCoupon(s.db.QueryRow("SELECT code, promotion_id, status FROM coupons WHERE code = ?", id))
}

func (s *CouponStore) List() []domain.Coupon {
	result := make([]domain.Coupon, 0)
	rows, err := s.db.Query("SELECT code, promotion_id, status FROM coupons ORDER BY code")
	if err != nil {
		return result
	}
	defer rows.Close()
	for rows.Next() {
		value, err := scanCoupon(rows)
		if err != nil {
			return result
		}
		result = append(result, value)
	}
	return result
}

func scanCoupon(row interface{ Scan(dest ...any) error }) (domain.Coupon, error) {
	var value domain.Coupon

	if err := row.Scan(&value.Code, &value.PromotionId, &value.Status); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return domain.Coupon{}, ErrNotFound
		}
		return domain.Coupon{}, err
	}

	return value, nil
}

func formatStoredTime(value time.Time) string {
	if value.IsZero() {
		return ""
	}
	return value.UTC().Format(time.RFC3339Nano)
}

func parseStoredTime(raw string) time.Time {
	parsed, err := time.Parse(time.RFC3339Nano, raw)
	if err != nil {
		return time.Time{}
	}
	return parsed
}

func storedBool(value bool) int64 {
	if value {
		return 1
	}
	return 0
}
