// Code generated by LORD. DO NOT EDIT.
package compute

import "github.com/marianoceneri/promo-api/internal/domain"

// Engine is the boundary between contract-governed structure and the business
// logic LORD does not generate. Implement it in an unmanaged file; the
// generated handlers verify every contractual invariant around your result.
type Engine interface {
	// QuoteCart computes el importe final de un carrito tras acumular las promociones publicadas, habilitadas y vigentes al instante de la cotización
	//
	// The contract holds this result to the following invariants, which are
	// enforced on every response; violating them fails the request:
	//   - PR-DISCOUNT-NON-NEGATIVE: discount_cents is never negative
	//   - PR-DISCOUNT-BOUNDED: discount_cents never exceeds subtotal_cents
	//   - PR-TOTAL-CONSISTENT: total_cents equals subtotal_cents minus discount_cents
	//   - PR-BREAKDOWN-ADDS-UP: discount_cents equals the sum of applied[].discount_cents
	QuoteCart(request domain.QuoteRequest, promotions []domain.Promotion) (domain.Quote, error)
}
