// Code generated by LORD. DO NOT EDIT.
package compute_test

import (
	"encoding/json"
	"fmt"
	"testing"

	"github.com/marianoceneri/promo-api/internal/compute"
	"github.com/marianoceneri/promo-api/internal/domain"
)

func TestQuoteCartInvariantsRejectViolations(t *testing.T) {
	t.Run("PR-DISCOUNT-NON-NEGATIVE", func(t *testing.T) {
		if err := compute.VerifyQuoteCart(domain.Quote{DiscountCents: -1}); err == nil {
			t.Fatalf("PR-DISCOUNT-NON-NEGATIVE must be rejected: discount_cents is never negative")
		}
	})
	t.Run("PR-DISCOUNT-BOUNDED", func(t *testing.T) {
		if err := compute.VerifyQuoteCart(domain.Quote{DiscountCents: 10, SubtotalCents: 1}); err == nil {
			t.Fatalf("PR-DISCOUNT-BOUNDED must be rejected: discount_cents never exceeds subtotal_cents")
		}
	})
	t.Run("PR-TOTAL-CONSISTENT", func(t *testing.T) {
		if err := compute.VerifyQuoteCart(domain.Quote{TotalCents: 999, SubtotalCents: 10, DiscountCents: 1}); err == nil {
			t.Fatalf("PR-TOTAL-CONSISTENT must be rejected: total_cents equals subtotal_cents minus discount_cents")
		}
	})
	t.Run("PR-BREAKDOWN-ADDS-UP", func(t *testing.T) {
		if err := compute.VerifyQuoteCart(domain.Quote{DiscountCents: 999, Applied: []domain.AppliedPromotion{{DiscountCents: 1}}}); err == nil {
			t.Fatalf("PR-BREAKDOWN-ADDS-UP must be rejected: discount_cents equals the sum of applied[].discount_cents")
		}
	})
}

func TestQuoteCartEXSINPROMOS(t *testing.T) {
	// un carrito de 2000 sin promociones aplicables paga 2000
	var request domain.QuoteRequest
	if err := json.Unmarshal([]byte("{\"at\":\"2026-06-01T12:00:00Z\",\"items\":[{\"sku\":\"A\",\"quantity\":1,\"unit_price_cents\":2000}]}"), &request); err != nil {
		t.Fatal(err)
	}
	var promotions []domain.Promotion
	if err := json.Unmarshal([]byte("[]"), &promotions); err != nil {
		t.Fatal(err)
	}
	result, err := compute.NewBusinessEngine().QuoteCart(request, promotions)
	if err != nil {
		t.Fatalf("EX-SIN-PROMOS: %v", err)
	}
	if err := compute.VerifyQuoteCart(result); err != nil {
		t.Fatalf("EX-SIN-PROMOS violates its contract: %v", err)
	}
	actual, err := json.Marshal(result)
	if err != nil {
		t.Fatal(err)
	}
	var got, want map[string]any
	if err := json.Unmarshal(actual, &got); err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal([]byte("{\"subtotal_cents\":2000,\"discount_cents\":0,\"total_cents\":2000}"), &want); err != nil {
		t.Fatal(err)
	}
	for key, expected := range want {
		if fmt.Sprint(got[key]) != fmt.Sprint(expected) {
			t.Fatalf("EX-SIN-PROMOS: %s = %v, want %v", key, got[key], expected)
		}
	}
}

func TestQuoteCartEXMITAD(t *testing.T) {
	// una promoción del 50% sobre un carrito de 2000 deja 1000
	var request domain.QuoteRequest
	if err := json.Unmarshal([]byte("{\"at\":\"2026-06-01T12:00:00Z\",\"items\":[{\"sku\":\"A\",\"quantity\":2,\"unit_price_cents\":1000}]}"), &request); err != nil {
		t.Fatal(err)
	}
	var promotions []domain.Promotion
	if err := json.Unmarshal([]byte("[{\"id\":\"P-50\",\"name\":\"mitad\",\"starts_at\":\"2026-01-01T00:00:00Z\",\"ends_at\":\"2027-01-01T00:00:00Z\",\"installments\":1,\"discount_percent\":50,\"enabled\":true,\"status\":\"published\"}]"), &promotions); err != nil {
		t.Fatal(err)
	}
	result, err := compute.NewBusinessEngine().QuoteCart(request, promotions)
	if err != nil {
		t.Fatalf("EX-MITAD: %v", err)
	}
	if err := compute.VerifyQuoteCart(result); err != nil {
		t.Fatalf("EX-MITAD violates its contract: %v", err)
	}
	actual, err := json.Marshal(result)
	if err != nil {
		t.Fatal(err)
	}
	var got, want map[string]any
	if err := json.Unmarshal(actual, &got); err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal([]byte("{\"subtotal_cents\":2000,\"discount_cents\":1000,\"total_cents\":1000}"), &want); err != nil {
		t.Fatal(err)
	}
	for key, expected := range want {
		if fmt.Sprint(got[key]) != fmt.Sprint(expected) {
			t.Fatalf("EX-MITAD: %s = %v, want %v", key, got[key], expected)
		}
	}
}

func TestQuoteCartEXTOPECERO(t *testing.T) {
	// varias promociones que acumulan más que el carrito lo dejan en cero
	var request domain.QuoteRequest
	if err := json.Unmarshal([]byte("{\"at\":\"2026-06-01T12:00:00Z\",\"items\":[{\"sku\":\"A\",\"quantity\":1,\"unit_price_cents\":2000}]}"), &request); err != nil {
		t.Fatal(err)
	}
	var promotions []domain.Promotion
	if err := json.Unmarshal([]byte("[{\"id\":\"P-60\",\"name\":\"sesenta\",\"starts_at\":\"2026-01-01T00:00:00Z\",\"ends_at\":\"2027-01-01T00:00:00Z\",\"installments\":1,\"discount_percent\":60,\"enabled\":true,\"status\":\"published\"},{\"id\":\"P-70\",\"name\":\"setenta\",\"starts_at\":\"2026-01-01T00:00:00Z\",\"ends_at\":\"2027-01-01T00:00:00Z\",\"installments\":1,\"discount_percent\":70,\"enabled\":true,\"status\":\"published\"}]"), &promotions); err != nil {
		t.Fatal(err)
	}
	result, err := compute.NewBusinessEngine().QuoteCart(request, promotions)
	if err != nil {
		t.Fatalf("EX-TOPE-CERO: %v", err)
	}
	if err := compute.VerifyQuoteCart(result); err != nil {
		t.Fatalf("EX-TOPE-CERO violates its contract: %v", err)
	}
	actual, err := json.Marshal(result)
	if err != nil {
		t.Fatal(err)
	}
	var got, want map[string]any
	if err := json.Unmarshal(actual, &got); err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal([]byte("{\"subtotal_cents\":2000,\"discount_cents\":2000,\"total_cents\":0}"), &want); err != nil {
		t.Fatal(err)
	}
	for key, expected := range want {
		if fmt.Sprint(got[key]) != fmt.Sprint(expected) {
			t.Fatalf("EX-TOPE-CERO: %s = %v, want %v", key, got[key], expected)
		}
	}
}
