// Code generated by LORD. DO NOT EDIT.
package compute

import (
	"fmt"

	"github.com/marianoceneri/promo-api/internal/domain"
)

// VerifyQuoteCart enforces the contractual invariants of QuoteCart.
func VerifyQuoteCart(result domain.Quote) error {
	if result.DiscountCents < 0 {
		return fmt.Errorf("PR-DISCOUNT-NON-NEGATIVE: discount_cents is never negative")
	}
	if result.DiscountCents > result.SubtotalCents {
		return fmt.Errorf("PR-DISCOUNT-BOUNDED: discount_cents never exceeds subtotal_cents")
	}
	if result.TotalCents != result.SubtotalCents-result.DiscountCents {
		return fmt.Errorf("PR-TOTAL-CONSISTENT: total_cents equals subtotal_cents minus discount_cents")
	}
	sumDiscountCentsApplied := int64(0)
	for _, item := range result.Applied {
		sumDiscountCentsApplied += item.DiscountCents
	}
	if result.DiscountCents != sumDiscountCentsApplied {
		return fmt.Errorf("PR-BREAKDOWN-ADDS-UP: discount_cents equals the sum of applied[].discount_cents")
	}
	return nil
}
