// Code generated by LORD. DO NOT EDIT.
package domain

import "time"

type Promotion struct {
	Id              string    `json:"id"`
	Name            string    `json:"name"`
	StartsAt        time.Time `json:"starts_at"`
	EndsAt          time.Time `json:"ends_at"`
	Installments    int64     `json:"installments"`
	DiscountPercent int64     `json:"discount_percent"`
	Enabled         bool      `json:"enabled"`
	Status          string    `json:"status"`
}
