// Code generated by LORD. DO NOT EDIT.
package observability

import (
	"sync"
	"time"
)

type Event struct {
	Type string         `json:"type"`
	At   time.Time      `json:"at"`
	Data map[string]any `json:"data,omitempty"`
}

type Recorder struct {
	mu              sync.RWMutex
	events          []Event
	historyComplete bool
}

func NewRecorder() *Recorder { return &Recorder{historyComplete: true} }

func (r *Recorder) Record(eventType string, data map[string]any) {
	r.mu.Lock()
	defer r.mu.Unlock()
	event := Event{Type: eventType, At: time.Now().UTC(), Data: data}
	r.events = append(r.events, event)
}

func (r *Recorder) Snapshot() []Event {
	r.mu.RLock()
	defer r.mu.RUnlock()
	result := make([]Event, len(r.events))
	copy(result, r.events)
	return result
}

// MarkHistoryIncomplete records that events happened before this process
// started (persistent state predates the recorder); verifications must not
// assume a complete history.
func (r *Recorder) MarkHistoryIncomplete() {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.historyComplete = false
}

func (r *Recorder) HistoryComplete() bool {
	r.mu.RLock()
	defer r.mu.RUnlock()
	return r.historyComplete
}
