// Code generated by LORD. DO NOT EDIT.
package observability

import (
	"sync"
	"time"
)

type Event struct {
	Type string         `json:"type"`
	At   time.Time      `json:"at"`
	Data map[string]any `json:"data,omitempty"`
}

type Recorder struct {
	mu     sync.RWMutex
	events []Event
}

func NewRecorder() *Recorder { return &Recorder{} }

func (r *Recorder) Record(eventType string, data map[string]any) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.events = append(r.events, Event{Type: eventType, At: time.Now().UTC(), Data: data})
}

func (r *Recorder) Snapshot() []Event {
	r.mu.RLock()
	defer r.mu.RUnlock()
	result := make([]Event, len(r.events))
	copy(result, r.events)
	return result
}
